name: note_recognizer_flutter
description: Android note and chord recognizer based on calibrated templates.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  path_provider: ^2.10.0
  permission_handler: ^11.3.1
  record: ^5.2.1
  shared_preferences: ^2.4.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
